// Generated by CoffeeScript 1.3.1
(function() {

  this.Add = function(input) {
    var delimeter, i, match, negatives, nums, splitter, sum;
    if (input === "") {
      return 0;
    }
    delimeter = new RegExp("//(.*)\n(.*)");
    splitter = new RegExp(/[,|\n]/);
    match = input.match(delimeter);
    if (match) {
      delimeter = match[1];
      input = match[2];
      splitter = new RegExp("[,|\n|" + delimeter + "]");
    }
    nums = input.split(splitter);
    sum = 0;
    negatives = [];
    i = nums.length - 1;
    while (i >= 0) {
      if (nums[i] < 0) {
        negatives.push(nums[i]);
      }
      if (nums[i] <= 1000) {
        sum += parseInt(nums[i], 10);
      }
      i--;
    }
    if (negatives.length > 0) {
      throw new Error("negatives not allowed: " + negatives.reverse().join());
    }
    return sum;
  };

}).call(this);
