// Generated by CoffeeScript 1.3.1
(function() {

  this.Add = function(input) {
    var delimeter, match, nums, sum;
    if (input === "") {
      return 0;
    }
    delimeter = input.split(/(.*)\n(.*)/);
    match = input.match(delimeter);
    nums = input.split(/[,|\n]/);
    if (nums.length === 1) {
      return parseInt(nums[0], 10);
    }
    return sum = nums.reduce(function(t, s) {
      return parseInt(t, 10) + parseInt(s, 10);
    });
  };

}).call(this);
